# REUSE (https://reuse.software, spec 3.3) — one license for the whole
# repository: Apache-2.0. A managed project's knowledge lives in the
# project's own repository under its own license (<working copy>/
# .agent-fabric/memory/), never here; projects/<id>/ here holds a project's
# binding and integration material, which the license holder placed under
# this repository's license on 2026-09-14. projects/registry.json records
# each project's OWN license as information about that project's tree.
version = 1
SPDX-PackageName = "agent-fabric"
SPDX-PackageSupplier = "Andrea Benetton"
SPDX-PackageDownloadLocation = "https://github.com/gzapi-org/agent-fabric-public"

[[annotations]]
path = ["**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Andrea Benetton"
SPDX-License-Identifier = "Apache-2.0"
